---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Redis server
  become: yes
  apt:
    name: redis-server
    state: present


- name: Configure Redis master
  template:
    src: "template/redis_master.conf.j2"
    dest: /etc/redis/redis.conf
  notify: restart redis-server
      
- name: Install Redis Sentinel
  apt:
    name: redis-sentinel
    state: present    
     
- name: Configure Redis Sentinel
  template:
    src: template/sentinel.conf.j2
    dest: /etc/redis/sentinel.conf   
  notify: restart redis-sentinel    
