---
- name: Include tasks based on instance tags
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/configure_master.yml"  # Adjust the path as needed
    - "{{ role_path }}/tasks/configure_slave.yml"   # Adjust the path as needed

