---
- include_tasks: configure_master.yml
  when: "'master_redis' in hostvars[inventory_hostname].tags.Name"

- include_tasks: configure_slave.yml
  when: "'slave_redis' in hostvars[inventory_hostname].tags.Name"

